version: '3.5'
volumes:
  gems:
services:
  ahoy:
    image: ruby:2.5
    working_dir: /home/app
    volumes:
      - gems:/usr/local/bundle
      - ./:/home/app
    links:
      - db
    command: rspec
  db:
    image: mysql:5.7
    command: "--sql-mode='NO_ENGINE_SUBSTITUTION'"
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
