version: '3.5'
volumes:
  gems:
services:
  app:
    image: ruby:2.5
    working_dir: /home/app
    volumes:
      - gems:/usr/local/bundle
      - ./:/home/app
    command: rake test
    environment:
      - VERBOSE=true
